version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    depends_on:
      - mongodb
    build: 
      context: Back_End
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  ui:
    image: ui
    depends_on:
      - api
    build:
      context: FRONTEND
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173

volumes:
  mongo_volume: